services:
  netdoc:
    image: ghcr.io/photoncody/netdoc:latest
    # build: .
    container_name: netdoc
    ports:
      - "8080:80"
    #environment:
    # - NETDOC_USER=admin
    # - NETDOC_PASSWORD=securepassword123 
    # Uncomment and set these environment variables to enable authentication, otherwise the application will run without authentication.
    volumes:
      - netdoc_data:/data
    restart: unless-stopped

volumes:
  netdoc_data: